---
- hosts: all
  pre_tasks:
  tasks:
    - name: 'Verify Ansible meets AAF Installer version requirments.'
      assert:
        that: "ansible_version.full is version_compare('2.9', '>=')"
        msg: "You must update Ansible to at least 2.9 to use this version of the AAF IdP Installer."

- hosts: idp_servers
  vars:
    installer:
      root: "{{ install_base }}/shibboleth-idp5-installer"
      path: "{{ install_base }}/shibboleth-idp5-installer/build"
      repository: "{{ install_base }}/shibboleth-idp5-installer/repository"
  tasks:
    - name: 'Copy example files to assets only if they do not exist'
      copy:
        src: '{{ installer.repository }}/assets/idp.example.edu.dist/'
        dest: '{{ installer.repository }}/assets/{{inventory_hostname}}'
        force: no
